spring:

  application:
    name: document-render-service

  service:
    path:
      prefix: /document-render-java

management:
  endpoints:
    web:
      exposure:
        include: health
      base-path: /document-render-service
      path-mapping:
        health: healthcheck
  endpoint:
    health:
      access: read_only
      show-details: always
  health:
    defaults:
      enabled: true
    mongo:
      enabled: false

server:
  port: ${PORT:8181}
